source "https://rubygems.org"

gem "terraspace", "~> 2.2.0"
# gem "terraspace_plugin_aws"
gem "rspec-terraspace"

# Uncomment the ci and vcs provider you wish to use. Should use both ci and vcs gem
# Docs: https://terraspace.cloud/docs/ci/
# gem "terraspace_ci_github"    # gathers info from ci env
# gem "terraspace_vcs_github"   # post comment on pr
