name: Pytest check

on:
  pull_request:
    branches:
      - "*"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip install -r requirements_prod.txt
      - name: Test with pytest
        run: |
          pytest src/tests/
